// Captions in the shape the real captioner would return (one JSON object per sticker).
const A = true;
window.STICKERS = [
 {id:1, c:"A donkey stares up into the camera with a wide-angle face.", e:"awkward", t:["donkey","animal","stare","confused"]},
 {id:2, c:"A yellow 3D emoji closes its eyes and rests a fist on its chin. It holds back a comment.", e:"smug", t:["emoji","smug","thinking","holding back"], a:A},
 {id:3, c:"A dark purple hedgehog creature claps slowly in the dark.", e:"sinister", t:["evil","plotting","clap","villain"], a:A},
 {id:4, c:"A blue mouse puppet with big ears stands still and looks innocent.", e:"innocent", t:["mouse","awkward","innocent","standing"]},
 {id:5, c:"A baby in a red beanie gives a side-eye smirk.", e:"smug", t:["baby","side-eye","smirk","judging"]},
 {id:6, c:"A man with headphones closes his eyes in disappointment.", e:"disappointed", t:["disappointed","sigh","tired","headphones"], a:A},
 {id:7, c:"A grey and white cat leans into the camera.", e:"curious", t:["cat","curious","close","hello"], a:A},
 {id:8, c:"A hamster with pink bows and long eyelashes stares into the camera.", e:"sad-cute", t:["hamster","cute","bows","sad","stare"]},
 {id:9, c:"A young man in a cap laughs and covers his mouth.", e:"amused", t:["laughing","giggle","funny"]},
 {id:10, c:"A person makes a shaka hand sign at a webcam.", e:"relaxed", t:["shaka","greeting","hang loose","hello"]},
 {id:11, c:"A person makes a rock hand sign in a selfie.", e:"cool", t:["rock","cool","selfie"]},
 {id:12, c:"A cat has a pink heart on its nose and looks in love.", e:"loving", t:["cat","love","heart","cute","aww"]},
 {id:13, c:"A yellow emoji sticks out a long tongue and throws both hands up.", e:"silly", t:["emoji","silly","crazy","tongue"]},
 {id:14, c:"A black puppy gives a startled side glance with wide eyes.", e:"startled", t:["dog","puppy","shocked","side-eye","caught"]},
 {id:15, c:"A cobra with drawn stick arms puts its hands on its hips.", e:"sassy", t:["snake","sassy","waiting","well?"]},
 {id:16, c:"A blushing cat with two pointing-finger emojis looks shy.", e:"shy", t:["cat","shy","asking","please","fingers"]},
 {id:17, c:"A red 3D emoji clenches its fists and grits its teeth.", e:"angry", t:["emoji","angry","rage","mad"], a:A},
 {id:18, c:"A man squints at the camera in a close-up. He does not believe it.", e:"skeptical", t:["skeptical","doubt","really","squint"], a:A},
 {id:19, c:"Patrick Star stares with a wide open mouth.", e:"shocked", t:["patrick","spongebob","shocked","speechless"]},
 {id:20, c:"A stick figure holds up two glasses of Aperol Spritz.", e:"happy", t:["flork","aperol","drinks","cheers","party","weekend"]},
 {id:21, c:"A blurry cat stands upright behind a door and peeks out.", e:"sneaky", t:["cat","lurking","peek","hiding"], a:A},
 {id:22, c:"A dog pushes its nose into a fisheye lens with wide eyes.", e:"curious", t:["dog","nose","close-up","curious","what"]},
 {id:23, c:"A white cat folds human hands on a sofa. The mood is serious.", x:"Wir müssen reden...", e:"serious", t:["cat","serious","talk","german","uh-oh"]},
 {id:24, c:"A cat gives a thumbs up with a human hand.", e:"approving", t:["cat","thumbs up","ok","approve","nice"]},
 {id:25, c:"A yellow emoji looks to the side with one large eye.", e:"suspicious", t:["emoji","side-eye","suspicious","hmm"], a:A},
 {id:26, c:"A cat with round glasses raises one finger to correct you.", e:"pedantic", t:["cat","nerd","actually","glasses","correction"]},
 {id:27, c:"A green radar screen sweeps in a circle.", e:"alert", t:["radar","scanning","searching","detect"], a:A},
 {id:28, c:"A yellow 3D emoji walks away with an unimpressed hand gesture.", e:"unimpressed", t:["emoji","whatever","leaving","unimpressed"], a:A},
 {id:29, c:"A nerd emoji with glasses and buck teeth holds up its hands.", e:"nerdy", t:["emoji","nerd","glasses","actually"], a:A},
 {id:30, c:"Three small cats dance on their back legs.", e:"joyful", t:["cat","dance","party","celebrate"], a:A},
 {id:31, c:"A man in a suit spreads his arms in a wide welcome.", e:"showy", t:["suit","ta-da","welcome","shrug"], a:A},
 {id:32, c:"Two men in black and white squeeze their eyes shut and press their hands together.", e:"pleading", t:["praying","please","hoping","laughing"], a:A},
 {id:33, c:"A gauge labelled cortisol points to high.", x:"CORTISOL", e:"stressed", t:["cortisol","stress","high","panic","deadline"]},
 {id:34, c:"A yellow candy character types on an old grey computer.", e:"busy", t:["typing","working","computer","coding","busy"], a:A},
 {id:35, c:"A blurry cat gasps with a wide open mouth.", e:"shocked", t:["cat","gasp","shocked","omg"]},
 {id:36, c:"A gauge labelled cortisol points to low.", x:"CORTISOL", e:"calm", t:["cortisol","calm","relaxed","low","chill"]},
 {id:37, c:"The White Rabbit holds up a pocket watch.", e:"rushed", t:["rabbit","late","time","hurry","alice"]},
 {id:38, c:"A single cat dances on its back legs.", e:"joyful", t:["cat","dance","happy","celebrate"], a:A},
 {id:39, c:"A stick figure pats a sad stick figure on the head.", x:"PAT PAT", e:"comforting", t:["flork","comfort","pat","there there","sorry"]},
 {id:40, c:"A yellow 3D emoji carries a folding chair and gets ready to swing it.", e:"threatening", t:["emoji","chair","fight","threat","joke"]},
];
// Stand-in for the embedding model: related words pull the same stickers.
window.NEAR = {
 stressed:["cortisol","stress","panic","deadline"], stress:["cortisol","panic"], deadline:["cortisol","typing","late"],
 drunk:["aperol","drinks","cheers"], friday:["aperol","party","dance","weekend"], beer:["drinks","cheers"], celebrate:["dance","party","cheers"],
 "talk":["serious","reden","uh-oh","caught","skeptical"], reden:["serious","talk"], trouble:["serious","uh-oh","caught"],
 sus:["side-eye","suspicious","skeptical"], doubt:["skeptical","side-eye","squint"], lying:["skeptical","side-eye"], judging:["side-eye","smirk","unimpressed"],
 sorry:["comfort","pat","shy"], sad:["comfort","sad","disappointed"], hug:["comfort","love","pat"],
 yes:["thumbs up","approve","ok"], agree:["thumbs up","approve"], good:["thumbs up","nice"],
 wtf:["shocked","gasp","speechless","confused"], omg:["shocked","gasp"], surprised:["shocked","startled","gasp"],
 mad:["angry","rage","chair"], angry:["rage","mad","chair","fight"], fight:["chair","angry"],
 late:["rabbit","time","hurry"], work:["typing","computer","busy"], coding:["typing","computer"],
 smartass:["nerd","actually","correction"], akshually:["nerd","actually"], please:["shy","praying","asking"],
 love:["heart","cute","aww"], cute:["love","bows","aww"], bye:["leaving","whatever"], evil:["plotting","villain","sinister"], looking:["radar","searching","lurking","peek"],
};
// User-defined smart packs. "rule" is what the user typed. "tags" stands in for the model's reading of that rule.
window.PACKS = [
 {id:"work",  name:"Work stress", rule:"Deadlines, too much work, being late, being tired of it all", tags:["cortisol","typing","late","disappointed","deadline","busy","sigh"], refresh:"Every night", mac:true, phone:true},
 {id:"react", name:"Reactions",   rule:"Short reactions: shock, doubt, side-eye, approval", tags:["shocked","side-eye","skeptical","thumbs up","gasp","suspicious","unimpressed","smug"], refresh:"Every night", mac:true, phone:true},
 {id:"cats",  name:"Cats",        rule:"Every sticker with a cat", tags:["cat"], refresh:"When I save a sticker", mac:true, phone:true},
 {id:"party", name:"Weekend",     rule:"Drinks, dancing, good news, celebrating", tags:["aperol","dance","cheers","party","celebrate","silly"], refresh:"Every week", mac:true, phone:false},
 {id:"soft",  name:"Be nice",     rule:"Comfort, love, saying sorry, asking for a favour", tags:["comfort","love","shy","praying","cute","heart"], refresh:"Every night", mac:true, phone:false},
];
